server:
  port: '8020'

application:
  jwtSecret: RamPhotoApp
  jwtExpirationMs: 180000
  
eureka:
  instance:
    preferIpAddress: 'true'
  client:
    fetchRegistry: 'true'
    registerWithEureka: 'true'
    serviceUrl:
      defaultZone: 'http://localhost:8010/eureka/'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  
spring:
  datasource:
    hikari:
        initialization-fail-timeout: 0
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/photo?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
        ddl-auto: update
  cloud:
    gateway:
      discovery:
        locator:
#          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: 'auth-api'
        uri: 'lb://PHOTOUSERSAPI'
        predicates:
        - Path=/photo/users/auth/**
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/photo/users/(?<segment>.*), /$\{segment}
      - id: 'users-read-api'
        uri: 'lb://PHOTOUSERSAPI'
        predicates:
        - Path=/photo/users/user/**
        - Header=Role, USER
        - Method=GET
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/photo/users/(?<segment>.*), /$\{segment}
        - AuthFilterFactory
      - id: 'users-modify-api'
        uri: 'lb://PHOTOUSERSAPI'
        predicates:
        - Path=/photo/users/user/**
        - Header=Role, ADMIN
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/photo/users/(?<segment>.*), /$\{segment}
        - AuthFilterFactory
      - id: 'accounts-api'
        uri: 'lb://PHOTOACCOUNTSAPI'
        predicates:
        - Path=/photo/accounts/**
        - Header=Role, ADMIN
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/photo/accounts/(?<segment>.*), /$\{segment}
        - AuthFilterFactory
  
  
